//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int id { get; set; }
        public string llave { get; set; }
        public string clave { get; set; }
        public string nombre { get; set; }
        public string fecha { get; set; }
        public string cuenta { get; set; }
        public string contrasena { get; set; }
        public string perfiles { get; set; }
        public string grupos { get; set; }
        public string privilegios { get; set; }
        public string idEstacionTrabajo { get; set; }
        public string tema { get; set; }
        public Nullable<int> idIdioma { get; set; }
        public Nullable<int> sesiones { get; set; }
        public Nullable<int> intentos { get; set; }
        public Nullable<short> expira { get; set; }
        public string fechaVigencia { get; set; }
        public Nullable<int> idUsuarioSuperior { get; set; }
        public Nullable<int> idSuscriptor { get; set; }
        public string fechaEstatus { get; set; }
        public Nullable<short> estatus { get; set; }
    }
}
